# https://www.ntweekly.com/2022/07/25/how-to-create-a-bastion-host-on-azure-with-terraform/

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformInstaller@0
  displayName: 'TF Install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV3@3
  displayName: 'TF Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'S1-Visual Studio Ultimate with MSDN(ae9cebbc-dc9d-49d8-a130-5b68cddefa15)'
    backendAzureRmResourceGroupName: 'S1-RG-CORE'
    backendAzureRmStorageAccountName: 'storageaccounts1core'
    backendAzureRmContainerName: 'containers1coretf'
    backendAzureRmKey: 'project08-main.tf'

- task: TerraformTaskV3@3
  displayName: 'TF Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'S1-Visual Studio Ultimate with MSDN(ae9cebbc-dc9d-49d8-a130-5b68cddefa15)'

- task: TerraformTaskV3@3
  displayName: 'TF Deploy'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'S1-Visual Studio Ultimate with MSDN(ae9cebbc-dc9d-49d8-a130-5b68cddefa15)'
    